---
argument_specs:
  main:
    short_description: Enforce the Atlas UTC time baseline
    options:
      atlas_time_timezone:
        type: str
        choices:
          - Etc/UTC
        default: Etc/UTC
