---
cloudfall_logging_collector_stack: {}
cloudfall_logging_collector_metrics_role: alloy
cloudfall_logging_collector_grafana_repository_key_url: >-
  https://apt.grafana.com/gpg-full.key
cloudfall_logging_collector_grafana_repository_key_path: /etc/apt/keyrings/grafana.asc
cloudfall_logging_collector_grafana_repository_url: https://apt.grafana.com
